//! Shipped real-world city maps and urban racing championships.
//!
//! Generated by `tools/track_cook/openmap_downloader.py`.
//! Fully `#![no_std]` and pure `core` compatible with static memory footprint.

use crate::city::{CityDef, CityRace, DEFAULT_CHUNK_DIM, DEFAULT_TEXELS_PER_CELL};
use crate::math::{Fixed, Vec2};
use crate::timing::{CheckpointGate, ParTimes};

/// Authored urban racing circuits for Cape Town.
pub static CAPE_TOWN_RACES: &[CityRace] = &[
    CityRace {
        name: "Waterfront GP",
        district: "V&A Waterfront",
        start_pos: Vec2::new(Fixed::from_int(2448), Fixed::from_int(1232)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 76,
            y: 38,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2050,
            silver_ticks: 1720,
            gold_ticks: 1480,
            dev_platinum_ticks: 1184,
        },
        checkpoints: &CAPE_TOWN_RACE_0_CHECKPOINTS,
        route: &CAPE_TOWN_RACE_0_ROUTE,
        half_width: 32,
    },
    CityRace {
        name: "Atlantic Seaboard Blast",
        district: "Green Point",
        start_pos: Vec2::new(Fixed::from_int(1040), Fixed::from_int(912)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 32,
            y: 28,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2200,
            silver_ticks: 1850,
            gold_ticks: 1600,
            dev_platinum_ticks: 1280,
        },
        checkpoints: &CAPE_TOWN_RACE_1_CHECKPOINTS,
        route: &CAPE_TOWN_RACE_1_ROUTE,
        half_width: 36,
    },
];

static CAPE_TOWN_RACE_0_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 76,
        y: 38,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 92,
        y: 42,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 86,
        y: 58,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 68,
        y: 55,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 58,
        y: 42,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 66,
        y: 36,
        width: 2,
        height: 4,
    },
];

static CAPE_TOWN_RACE_0_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(2448), Fixed::from_int(1232)),
    Vec2::new(Fixed::from_int(2960), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(2768), Fixed::from_int(1872)),
    Vec2::new(Fixed::from_int(2192), Fixed::from_int(1776)),
    Vec2::new(Fixed::from_int(1872), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(2128), Fixed::from_int(1168)),
];

static CAPE_TOWN_RACE_1_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 32,
        y: 28,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 54,
        y: 30,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 68,
        y: 36,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 60,
        y: 48,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 38,
        y: 45,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 26,
        y: 36,
        width: 2,
        height: 4,
    },
];

static CAPE_TOWN_RACE_1_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(1040), Fixed::from_int(912)),
    Vec2::new(Fixed::from_int(1744), Fixed::from_int(976)),
    Vec2::new(Fixed::from_int(2192), Fixed::from_int(1168)),
    Vec2::new(Fixed::from_int(1936), Fixed::from_int(1552)),
    Vec2::new(Fixed::from_int(1232), Fixed::from_int(1456)),
    Vec2::new(Fixed::from_int(848), Fixed::from_int(1168)),
];

/// Full city definition for Cape Town (South Africa).
pub static CITY_CAPE_TOWN: CityDef = CityDef::new(
    "Cape Town",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    -339450000,
    183900000,
    -338900000,
    184549999,
    CAPE_TOWN_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for Melbourne.
pub static MELBOURNE_RACES: &[CityRace] = &[
    CityRace {
        name: "Albert Park F1 Circuit",
        district: "Albert Park",
        start_pos: Vec2::new(Fixed::from_int(2256), Fixed::from_int(2512)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 70,
            y: 78,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2150,
            silver_ticks: 1800,
            gold_ticks: 1550,
            dev_platinum_ticks: 1240,
        },
        checkpoints: &MELBOURNE_RACE_0_CHECKPOINTS,
        route: &MELBOURNE_RACE_0_ROUTE,
        half_width: 36,
    },
    CityRace {
        name: "Docklands Night GP",
        district: "Docklands",
        start_pos: Vec2::new(Fixed::from_int(1136), Fixed::from_int(1040)),
        start_heading: 2048,
        start_gate: CheckpointGate {
            x: 35,
            y: 32,
            width: 2,
            height: 4,
        },
        par_times: ParTimes {
            bronze_ticks: 2000,
            silver_ticks: 1680,
            gold_ticks: 1420,
            dev_platinum_ticks: 1136,
        },
        checkpoints: &MELBOURNE_RACE_1_CHECKPOINTS,
        route: &MELBOURNE_RACE_1_ROUTE,
        half_width: 32,
    },
];

static MELBOURNE_RACE_0_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 70,
        y: 78,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 88,
        y: 82,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 92,
        y: 104,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 78,
        y: 115,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 62,
        y: 108,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 56,
        y: 92,
        width: 2,
        height: 4,
    },
];

static MELBOURNE_RACE_0_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(2256), Fixed::from_int(2512)),
    Vec2::new(Fixed::from_int(2832), Fixed::from_int(2640)),
    Vec2::new(Fixed::from_int(2960), Fixed::from_int(3344)),
    Vec2::new(Fixed::from_int(2512), Fixed::from_int(3696)),
    Vec2::new(Fixed::from_int(2000), Fixed::from_int(3472)),
    Vec2::new(Fixed::from_int(1808), Fixed::from_int(2960)),
];

static MELBOURNE_RACE_1_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 35,
        y: 32,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 38,
        y: 48,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 52,
        y: 50,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 58,
        y: 34,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 48,
        y: 24,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 36,
        y: 25,
        width: 4,
        height: 2,
    },
];

static MELBOURNE_RACE_1_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(1136), Fixed::from_int(1040)),
    Vec2::new(Fixed::from_int(1232), Fixed::from_int(1552)),
    Vec2::new(Fixed::from_int(1680), Fixed::from_int(1616)),
    Vec2::new(Fixed::from_int(1872), Fixed::from_int(1104)),
    Vec2::new(Fixed::from_int(1552), Fixed::from_int(784)),
    Vec2::new(Fixed::from_int(1168), Fixed::from_int(816)),
];

/// Full city definition for Melbourne (Australia).
pub static CITY_MELBOURNE: CityDef = CityDef::new(
    "Melbourne",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    -378600000,
    1449300000,
    -378050000,
    1449950000,
    MELBOURNE_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for London.
pub static LONDON_RACES: &[CityRace] = &[
    CityRace {
        name: "Thames Embankment GP",
        district: "Westminster",
        start_pos: Vec2::new(Fixed::from_int(1456), Fixed::from_int(2000)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 45,
            y: 62,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2100,
            silver_ticks: 1750,
            gold_ticks: 1500,
            dev_platinum_ticks: 1200,
        },
        checkpoints: &LONDON_RACE_0_CHECKPOINTS,
        route: &LONDON_RACE_0_ROUTE,
        half_width: 32,
    },
    CityRace {
        name: "City of London Sprint",
        district: "The City",
        start_pos: Vec2::new(Fixed::from_int(2832), Fixed::from_int(1552)),
        start_heading: 2048,
        start_gate: CheckpointGate {
            x: 88,
            y: 48,
            width: 2,
            height: 4,
        },
        par_times: ParTimes {
            bronze_ticks: 1950,
            silver_ticks: 1620,
            gold_ticks: 1380,
            dev_platinum_ticks: 1104,
        },
        checkpoints: &LONDON_RACE_1_CHECKPOINTS,
        route: &LONDON_RACE_1_ROUTE,
        half_width: 28,
    },
];

static LONDON_RACE_0_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 45,
        y: 62,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 60,
        y: 55,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 75,
        y: 52,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 78,
        y: 68,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 62,
        y: 72,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 46,
        y: 70,
        width: 2,
        height: 4,
    },
];

static LONDON_RACE_0_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(1456), Fixed::from_int(2000)),
    Vec2::new(Fixed::from_int(1936), Fixed::from_int(1776)),
    Vec2::new(Fixed::from_int(2416), Fixed::from_int(1680)),
    Vec2::new(Fixed::from_int(2512), Fixed::from_int(2192)),
    Vec2::new(Fixed::from_int(2000), Fixed::from_int(2320)),
    Vec2::new(Fixed::from_int(1488), Fixed::from_int(2256)),
];

static LONDON_RACE_1_CHECKPOINTS: [CheckpointGate; 5] = [
    CheckpointGate {
        x: 88,
        y: 48,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 92,
        y: 64,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 108,
        y: 65,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 110,
        y: 46,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 98,
        y: 42,
        width: 2,
        height: 4,
    },
];

static LONDON_RACE_1_ROUTE: [Vec2; 5] = [
    Vec2::new(Fixed::from_int(2832), Fixed::from_int(1552)),
    Vec2::new(Fixed::from_int(2960), Fixed::from_int(2064)),
    Vec2::new(Fixed::from_int(3472), Fixed::from_int(2096)),
    Vec2::new(Fixed::from_int(3536), Fixed::from_int(1488)),
    Vec2::new(Fixed::from_int(3152), Fixed::from_int(1360)),
];

/// Full city definition for London (United Kingdom).
pub static CITY_LONDON: CityDef = CityDef::new(
    "London",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    514900000,
    -1500000,
    515300000,
    -700000,
    LONDON_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for Sydney.
pub static SYDNEY_RACES: &[CityRace] = &[
    CityRace {
        name: "Harbour Bridge GP",
        district: "The Rocks",
        start_pos: Vec2::new(Fixed::from_int(1552), Fixed::from_int(848)),
        start_heading: 2048,
        start_gate: CheckpointGate {
            x: 48,
            y: 26,
            width: 2,
            height: 4,
        },
        par_times: ParTimes {
            bronze_ticks: 2120,
            silver_ticks: 1780,
            gold_ticks: 1520,
            dev_platinum_ticks: 1216,
        },
        checkpoints: &SYDNEY_RACE_0_CHECKPOINTS,
        route: &SYDNEY_RACE_0_ROUTE,
        half_width: 36,
    },
    CityRace {
        name: "Botanic Bay Ring",
        district: "Botanic Gardens",
        start_pos: Vec2::new(Fixed::from_int(2320), Fixed::from_int(1936)),
        start_heading: 0,
        start_gate: CheckpointGate {
            x: 72,
            y: 60,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2040,
            silver_ticks: 1700,
            gold_ticks: 1450,
            dev_platinum_ticks: 1160,
        },
        checkpoints: &SYDNEY_RACE_1_CHECKPOINTS,
        route: &SYDNEY_RACE_1_ROUTE,
        half_width: 32,
    },
];

static SYDNEY_RACE_0_CHECKPOINTS: [CheckpointGate; 5] = [
    CheckpointGate {
        x: 48,
        y: 26,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 46,
        y: 48,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 58,
        y: 55,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 62,
        y: 38,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 52,
        y: 20,
        width: 2,
        height: 4,
    },
];

static SYDNEY_RACE_0_ROUTE: [Vec2; 5] = [
    Vec2::new(Fixed::from_int(1552), Fixed::from_int(848)),
    Vec2::new(Fixed::from_int(1488), Fixed::from_int(1552)),
    Vec2::new(Fixed::from_int(1872), Fixed::from_int(1776)),
    Vec2::new(Fixed::from_int(2000), Fixed::from_int(1232)),
    Vec2::new(Fixed::from_int(1680), Fixed::from_int(656)),
];

static SYDNEY_RACE_1_CHECKPOINTS: [CheckpointGate; 5] = [
    CheckpointGate {
        x: 72,
        y: 60,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 74,
        y: 42,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 88,
        y: 45,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 86,
        y: 68,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 75,
        y: 72,
        width: 4,
        height: 2,
    },
];

static SYDNEY_RACE_1_ROUTE: [Vec2; 5] = [
    Vec2::new(Fixed::from_int(2320), Fixed::from_int(1936)),
    Vec2::new(Fixed::from_int(2384), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(2832), Fixed::from_int(1456)),
    Vec2::new(Fixed::from_int(2768), Fixed::from_int(2192)),
    Vec2::new(Fixed::from_int(2416), Fixed::from_int(2320)),
];

/// Full city definition for Sydney (Australia).
pub static CITY_SYDNEY: CityDef = CityDef::new(
    "Sydney",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    -338850000,
    1511950000,
    -338400000,
    1512400000,
    SYDNEY_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for New York.
pub static NEW_YORK_RACES: &[CityRace] = &[
    CityRace {
        name: "Manhattan Grid GP",
        district: "Midtown Manhattan",
        start_pos: Vec2::new(Fixed::from_int(1680), Fixed::from_int(1456)),
        start_heading: 2048,
        start_gate: CheckpointGate {
            x: 52,
            y: 45,
            width: 2,
            height: 4,
        },
        par_times: ParTimes {
            bronze_ticks: 2180,
            silver_ticks: 1820,
            gold_ticks: 1580,
            dev_platinum_ticks: 1264,
        },
        checkpoints: &NEW_YORK_RACE_0_CHECKPOINTS,
        route: &NEW_YORK_RACE_0_ROUTE,
        half_width: 36,
    },
    CityRace {
        name: "Central Park Loop",
        district: "Central Park",
        start_pos: Vec2::new(Fixed::from_int(2064), Fixed::from_int(720)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 64,
            y: 22,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2060,
            silver_ticks: 1720,
            gold_ticks: 1480,
            dev_platinum_ticks: 1184,
        },
        checkpoints: &NEW_YORK_RACE_1_CHECKPOINTS,
        route: &NEW_YORK_RACE_1_ROUTE,
        half_width: 32,
    },
];

static NEW_YORK_RACE_0_CHECKPOINTS: [CheckpointGate; 5] = [
    CheckpointGate {
        x: 52,
        y: 45,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 54,
        y: 75,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 75,
        y: 72,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 72,
        y: 42,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 60,
        y: 44,
        width: 2,
        height: 4,
    },
];

static NEW_YORK_RACE_0_ROUTE: [Vec2; 5] = [
    Vec2::new(Fixed::from_int(1680), Fixed::from_int(1456)),
    Vec2::new(Fixed::from_int(1744), Fixed::from_int(2416)),
    Vec2::new(Fixed::from_int(2416), Fixed::from_int(2320)),
    Vec2::new(Fixed::from_int(2320), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(1936), Fixed::from_int(1424)),
];

static NEW_YORK_RACE_1_CHECKPOINTS: [CheckpointGate; 4] = [
    CheckpointGate {
        x: 64,
        y: 22,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 80,
        y: 25,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 78,
        y: 42,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 62,
        y: 40,
        width: 2,
        height: 4,
    },
];

static NEW_YORK_RACE_1_ROUTE: [Vec2; 4] = [
    Vec2::new(Fixed::from_int(2064), Fixed::from_int(720)),
    Vec2::new(Fixed::from_int(2576), Fixed::from_int(816)),
    Vec2::new(Fixed::from_int(2512), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(2000), Fixed::from_int(1296)),
];

/// Full city definition for New York (United States).
pub static CITY_NEW_YORK: CityDef = CityDef::new(
    "New York",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    407100000,
    -740200000,
    407700000,
    -739599999,
    NEW_YORK_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for Tokyo.
pub static TOKYO_RACES: &[CityRace] = &[
    CityRace {
        name: "Tokyo Bay Express",
        district: "Shuto Expressway",
        start_pos: Vec2::new(Fixed::from_int(1872), Fixed::from_int(2256)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 58,
            y: 70,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2140,
            silver_ticks: 1790,
            gold_ticks: 1540,
            dev_platinum_ticks: 1232,
        },
        checkpoints: &TOKYO_RACE_0_CHECKPOINTS,
        route: &TOKYO_RACE_0_ROUTE,
        half_width: 36,
    },
    CityRace {
        name: "Ginza Neon Circuit",
        district: "Ginza",
        start_pos: Vec2::new(Fixed::from_int(1808), Fixed::from_int(1232)),
        start_heading: 2048,
        start_gate: CheckpointGate {
            x: 56,
            y: 38,
            width: 2,
            height: 4,
        },
        par_times: ParTimes {
            bronze_ticks: 1980,
            silver_ticks: 1640,
            gold_ticks: 1400,
            dev_platinum_ticks: 1120,
        },
        checkpoints: &TOKYO_RACE_1_CHECKPOINTS,
        route: &TOKYO_RACE_1_ROUTE,
        half_width: 30,
    },
];

static TOKYO_RACE_0_CHECKPOINTS: [CheckpointGate; 5] = [
    CheckpointGate {
        x: 58,
        y: 70,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 80,
        y: 74,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 88,
        y: 92,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 72,
        y: 96,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 54,
        y: 86,
        width: 4,
        height: 2,
    },
];

static TOKYO_RACE_0_ROUTE: [Vec2; 5] = [
    Vec2::new(Fixed::from_int(1872), Fixed::from_int(2256)),
    Vec2::new(Fixed::from_int(2576), Fixed::from_int(2384)),
    Vec2::new(Fixed::from_int(2832), Fixed::from_int(2960)),
    Vec2::new(Fixed::from_int(2320), Fixed::from_int(3088)),
    Vec2::new(Fixed::from_int(1744), Fixed::from_int(2768)),
];

static TOKYO_RACE_1_CHECKPOINTS: [CheckpointGate; 4] = [
    CheckpointGate {
        x: 56,
        y: 38,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 60,
        y: 55,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 76,
        y: 52,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 72,
        y: 35,
        width: 4,
        height: 2,
    },
];

static TOKYO_RACE_1_ROUTE: [Vec2; 4] = [
    Vec2::new(Fixed::from_int(1808), Fixed::from_int(1232)),
    Vec2::new(Fixed::from_int(1936), Fixed::from_int(1776)),
    Vec2::new(Fixed::from_int(2448), Fixed::from_int(1680)),
    Vec2::new(Fixed::from_int(2320), Fixed::from_int(1136)),
];

/// Full city definition for Tokyo (Japan).
pub static CITY_TOKYO: CityDef = CityDef::new(
    "Tokyo",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    356350000,
    1397300000,
    356850000,
    1397900000,
    TOKYO_RACES,
    [(0, 0, 0); 256],
);

/// Authored urban racing circuits for Singapore.
pub static SINGAPORE_RACES: &[CityRace] = &[
    CityRace {
        name: "Marina Bay Street Circuit",
        district: "Marina Bay",
        start_pos: Vec2::new(Fixed::from_int(2000), Fixed::from_int(1360)),
        start_heading: 1024,
        start_gate: CheckpointGate {
            x: 62,
            y: 42,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2160,
            silver_ticks: 1810,
            gold_ticks: 1560,
            dev_platinum_ticks: 1248,
        },
        checkpoints: &SINGAPORE_RACE_0_CHECKPOINTS,
        route: &SINGAPORE_RACE_0_ROUTE,
        half_width: 36,
    },
    CityRace {
        name: "Downtown Core Sprint",
        district: "Downtown Core",
        start_pos: Vec2::new(Fixed::from_int(1360), Fixed::from_int(2256)),
        start_heading: 0,
        start_gate: CheckpointGate {
            x: 42,
            y: 70,
            width: 4,
            height: 2,
        },
        par_times: ParTimes {
            bronze_ticks: 2010,
            silver_ticks: 1660,
            gold_ticks: 1420,
            dev_platinum_ticks: 1136,
        },
        checkpoints: &SINGAPORE_RACE_1_CHECKPOINTS,
        route: &SINGAPORE_RACE_1_ROUTE,
        half_width: 30,
    },
];

static SINGAPORE_RACE_0_CHECKPOINTS: [CheckpointGate; 6] = [
    CheckpointGate {
        x: 62,
        y: 42,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 84,
        y: 40,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 86,
        y: 58,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 70,
        y: 62,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 54,
        y: 55,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 52,
        y: 44,
        width: 2,
        height: 4,
    },
];

static SINGAPORE_RACE_0_ROUTE: [Vec2; 6] = [
    Vec2::new(Fixed::from_int(2000), Fixed::from_int(1360)),
    Vec2::new(Fixed::from_int(2704), Fixed::from_int(1296)),
    Vec2::new(Fixed::from_int(2768), Fixed::from_int(1872)),
    Vec2::new(Fixed::from_int(2256), Fixed::from_int(2000)),
    Vec2::new(Fixed::from_int(1744), Fixed::from_int(1776)),
    Vec2::new(Fixed::from_int(1680), Fixed::from_int(1424)),
];

static SINGAPORE_RACE_1_CHECKPOINTS: [CheckpointGate; 4] = [
    CheckpointGate {
        x: 42,
        y: 70,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 44,
        y: 48,
        width: 2,
        height: 4,
    },
    CheckpointGate {
        x: 58,
        y: 52,
        width: 4,
        height: 2,
    },
    CheckpointGate {
        x: 56,
        y: 74,
        width: 2,
        height: 4,
    },
];

static SINGAPORE_RACE_1_ROUTE: [Vec2; 4] = [
    Vec2::new(Fixed::from_int(1360), Fixed::from_int(2256)),
    Vec2::new(Fixed::from_int(1424), Fixed::from_int(1552)),
    Vec2::new(Fixed::from_int(1872), Fixed::from_int(1680)),
    Vec2::new(Fixed::from_int(1808), Fixed::from_int(2384)),
];

/// Full city definition for Singapore (Singapore).
pub static CITY_SINGAPORE: CityDef = CityDef::new(
    "Singapore",
    128,
    128,
    DEFAULT_CHUNK_DIM,
    DEFAULT_TEXELS_PER_CELL,
    12750000,
    1038400000,
    13050000,
    1038750000,
    SINGAPORE_RACES,
    [(0, 0, 0); 256],
);

/// All real-world city maps ready for exploration and CD streaming.
pub static ALL_CITIES: &[&CityDef] = &[
    &CITY_CAPE_TOWN,
    &CITY_MELBOURNE,
    &CITY_LONDON,
    &CITY_SYDNEY,
    &CITY_NEW_YORK,
    &CITY_TOKYO,
    &CITY_SINGAPORE,
];
