//! Per-circuit visual texture metadata and decompression stream codec.
//!
//! Generated by `tools/track_cook/build_atlas.py`. Do not edit by hand.

/// Visual image width in texels.
pub const WIDTH: usize = 1280;
/// Visual image height in texels.
pub const HEIGHT: usize = 1280;
/// Tile dimension in texels (256x256 per page).
pub const TILE_DIM: usize = 256;
/// Number of tiles along X axis.
pub const TILES_X: usize = 5;
/// Number of tiles along Y axis.
pub const TILES_Y: usize = 5;
/// Total number of tiles per circuit.
pub const TILE_COUNT: usize = 25;
/// Number of authored circuits, one texture set each.
pub const COUNT: usize = 4;
/// Raw uncompressed 16-bit BGR555 halfword count per 256x256 tile (65,536).
pub const RAW_TILE_HALFWORDS: usize = TILE_DIM * TILE_DIM;
/// Raw uncompressed byte count per tile (131,072 bytes).
pub const RAW_TILE_BYTES: usize = RAW_TILE_HALFWORDS * 2;
/// Raw uncompressed 16-bit BGR555 halfword count per full track image.
pub const RAW_HALFWORDS: usize = WIDTH * HEIGHT;
/// Raw uncompressed byte count per full track image.
pub const RAW_BYTES: usize = RAW_HALFWORDS * 2;
/// Streaming ring buffer window size in bytes.
pub const STREAM_WINDOW: usize = 8192;
/// Name of the track visual asset file on the CD-ROM disc.
pub const TRACKS_BIN_NAME: &[u8] = b"TRACKS.BIN";

/// CD-ROM sector index entry for a compressed tile stream in TRACKS.BIN.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct TileSectorEntry {
    /// 2048-byte sector offset from the start of TRACKS.BIN.
    pub sector_offset: u32,
    /// Number of 2048-byte CD sectors allocated for this tile.
    pub sector_count: u32,
    /// Exact payload length of the compressed stream in bytes.
    pub byte_len: u32,
}

/// Streaming compressed 15-bit visual tile sector index [circuit][tile_idx].
pub static CIRCUIT_TILE_SECTORS: [[TileSectorEntry; TILE_COUNT]; COUNT] = [
    [
        TileSectorEntry {
            sector_offset: 0,
            sector_count: 2,
            byte_len: 2358,
        },
        TileSectorEntry {
            sector_offset: 2,
            sector_count: 2,
            byte_len: 2318,
        },
        TileSectorEntry {
            sector_offset: 4,
            sector_count: 2,
            byte_len: 2540,
        },
        TileSectorEntry {
            sector_offset: 6,
            sector_count: 2,
            byte_len: 2608,
        },
        TileSectorEntry {
            sector_offset: 8,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 10,
            sector_count: 2,
            byte_len: 2352,
        },
        TileSectorEntry {
            sector_offset: 12,
            sector_count: 2,
            byte_len: 2760,
        },
        TileSectorEntry {
            sector_offset: 14,
            sector_count: 2,
            byte_len: 2786,
        },
        TileSectorEntry {
            sector_offset: 16,
            sector_count: 2,
            byte_len: 2997,
        },
        TileSectorEntry {
            sector_offset: 18,
            sector_count: 2,
            byte_len: 2308,
        },
        TileSectorEntry {
            sector_offset: 20,
            sector_count: 2,
            byte_len: 2383,
        },
        TileSectorEntry {
            sector_offset: 22,
            sector_count: 2,
            byte_len: 3106,
        },
        TileSectorEntry {
            sector_offset: 24,
            sector_count: 2,
            byte_len: 2876,
        },
        TileSectorEntry {
            sector_offset: 26,
            sector_count: 2,
            byte_len: 3374,
        },
        TileSectorEntry {
            sector_offset: 28,
            sector_count: 2,
            byte_len: 2580,
        },
        TileSectorEntry {
            sector_offset: 30,
            sector_count: 2,
            byte_len: 2511,
        },
        TileSectorEntry {
            sector_offset: 32,
            sector_count: 2,
            byte_len: 2753,
        },
        TileSectorEntry {
            sector_offset: 34,
            sector_count: 2,
            byte_len: 2654,
        },
        TileSectorEntry {
            sector_offset: 36,
            sector_count: 2,
            byte_len: 2790,
        },
        TileSectorEntry {
            sector_offset: 38,
            sector_count: 2,
            byte_len: 2402,
        },
        TileSectorEntry {
            sector_offset: 40,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 42,
            sector_count: 2,
            byte_len: 2140,
        },
        TileSectorEntry {
            sector_offset: 44,
            sector_count: 2,
            byte_len: 2568,
        },
        TileSectorEntry {
            sector_offset: 46,
            sector_count: 2,
            byte_len: 2421,
        },
        TileSectorEntry {
            sector_offset: 48,
            sector_count: 2,
            byte_len: 2358,
        },
    ],
    [
        TileSectorEntry {
            sector_offset: 50,
            sector_count: 2,
            byte_len: 2358,
        },
        TileSectorEntry {
            sector_offset: 52,
            sector_count: 2,
            byte_len: 2318,
        },
        TileSectorEntry {
            sector_offset: 54,
            sector_count: 2,
            byte_len: 2540,
        },
        TileSectorEntry {
            sector_offset: 56,
            sector_count: 2,
            byte_len: 2608,
        },
        TileSectorEntry {
            sector_offset: 58,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 60,
            sector_count: 2,
            byte_len: 2489,
        },
        TileSectorEntry {
            sector_offset: 62,
            sector_count: 2,
            byte_len: 2875,
        },
        TileSectorEntry {
            sector_offset: 64,
            sector_count: 2,
            byte_len: 2598,
        },
        TileSectorEntry {
            sector_offset: 66,
            sector_count: 2,
            byte_len: 3131,
        },
        TileSectorEntry {
            sector_offset: 68,
            sector_count: 2,
            byte_len: 2452,
        },
        TileSectorEntry {
            sector_offset: 70,
            sector_count: 2,
            byte_len: 3264,
        },
        TileSectorEntry {
            sector_offset: 72,
            sector_count: 2,
            byte_len: 2912,
        },
        TileSectorEntry {
            sector_offset: 74,
            sector_count: 2,
            byte_len: 2925,
        },
        TileSectorEntry {
            sector_offset: 76,
            sector_count: 2,
            byte_len: 3115,
        },
        TileSectorEntry {
            sector_offset: 78,
            sector_count: 2,
            byte_len: 3390,
        },
        TileSectorEntry {
            sector_offset: 80,
            sector_count: 2,
            byte_len: 2705,
        },
        TileSectorEntry {
            sector_offset: 82,
            sector_count: 2,
            byte_len: 2690,
        },
        TileSectorEntry {
            sector_offset: 84,
            sector_count: 2,
            byte_len: 2832,
        },
        TileSectorEntry {
            sector_offset: 86,
            sector_count: 2,
            byte_len: 2614,
        },
        TileSectorEntry {
            sector_offset: 88,
            sector_count: 2,
            byte_len: 2680,
        },
        TileSectorEntry {
            sector_offset: 90,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 92,
            sector_count: 2,
            byte_len: 2140,
        },
        TileSectorEntry {
            sector_offset: 94,
            sector_count: 2,
            byte_len: 2568,
        },
        TileSectorEntry {
            sector_offset: 96,
            sector_count: 2,
            byte_len: 2421,
        },
        TileSectorEntry {
            sector_offset: 98,
            sector_count: 2,
            byte_len: 2358,
        },
    ],
    [
        TileSectorEntry {
            sector_offset: 100,
            sector_count: 2,
            byte_len: 2358,
        },
        TileSectorEntry {
            sector_offset: 102,
            sector_count: 2,
            byte_len: 2318,
        },
        TileSectorEntry {
            sector_offset: 104,
            sector_count: 2,
            byte_len: 2540,
        },
        TileSectorEntry {
            sector_offset: 106,
            sector_count: 2,
            byte_len: 2608,
        },
        TileSectorEntry {
            sector_offset: 108,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 110,
            sector_count: 2,
            byte_len: 2589,
        },
        TileSectorEntry {
            sector_offset: 112,
            sector_count: 2,
            byte_len: 2857,
        },
        TileSectorEntry {
            sector_offset: 114,
            sector_count: 2,
            byte_len: 2339,
        },
        TileSectorEntry {
            sector_offset: 116,
            sector_count: 2,
            byte_len: 2445,
        },
        TileSectorEntry {
            sector_offset: 118,
            sector_count: 2,
            byte_len: 2655,
        },
        TileSectorEntry {
            sector_offset: 120,
            sector_count: 2,
            byte_len: 3472,
        },
        TileSectorEntry {
            sector_offset: 122,
            sector_count: 2,
            byte_len: 3138,
        },
        TileSectorEntry {
            sector_offset: 124,
            sector_count: 2,
            byte_len: 2637,
        },
        TileSectorEntry {
            sector_offset: 126,
            sector_count: 2,
            byte_len: 3258,
        },
        TileSectorEntry {
            sector_offset: 128,
            sector_count: 2,
            byte_len: 3432,
        },
        TileSectorEntry {
            sector_offset: 130,
            sector_count: 2,
            byte_len: 2889,
        },
        TileSectorEntry {
            sector_offset: 132,
            sector_count: 2,
            byte_len: 2268,
        },
        TileSectorEntry {
            sector_offset: 134,
            sector_count: 2,
            byte_len: 2362,
        },
        TileSectorEntry {
            sector_offset: 136,
            sector_count: 2,
            byte_len: 2329,
        },
        TileSectorEntry {
            sector_offset: 138,
            sector_count: 2,
            byte_len: 2857,
        },
        TileSectorEntry {
            sector_offset: 140,
            sector_count: 2,
            byte_len: 2365,
        },
        TileSectorEntry {
            sector_offset: 142,
            sector_count: 2,
            byte_len: 2140,
        },
        TileSectorEntry {
            sector_offset: 144,
            sector_count: 2,
            byte_len: 2568,
        },
        TileSectorEntry {
            sector_offset: 146,
            sector_count: 2,
            byte_len: 2421,
        },
        TileSectorEntry {
            sector_offset: 148,
            sector_count: 2,
            byte_len: 2358,
        },
    ],
    [
        TileSectorEntry {
            sector_offset: 150,
            sector_count: 49,
            byte_len: 98425,
        },
        TileSectorEntry {
            sector_offset: 199,
            sector_count: 39,
            byte_len: 79283,
        },
        TileSectorEntry {
            sector_offset: 238,
            sector_count: 44,
            byte_len: 89777,
        },
        TileSectorEntry {
            sector_offset: 282,
            sector_count: 49,
            byte_len: 99112,
        },
        TileSectorEntry {
            sector_offset: 331,
            sector_count: 50,
            byte_len: 101811,
        },
        TileSectorEntry {
            sector_offset: 381,
            sector_count: 48,
            byte_len: 97886,
        },
        TileSectorEntry {
            sector_offset: 429,
            sector_count: 39,
            byte_len: 78472,
        },
        TileSectorEntry {
            sector_offset: 468,
            sector_count: 36,
            byte_len: 72178,
        },
        TileSectorEntry {
            sector_offset: 504,
            sector_count: 37,
            byte_len: 75597,
        },
        TileSectorEntry {
            sector_offset: 541,
            sector_count: 51,
            byte_len: 102657,
        },
        TileSectorEntry {
            sector_offset: 592,
            sector_count: 43,
            byte_len: 87465,
        },
        TileSectorEntry {
            sector_offset: 635,
            sector_count: 44,
            byte_len: 90079,
        },
        TileSectorEntry {
            sector_offset: 679,
            sector_count: 45,
            byte_len: 91776,
        },
        TileSectorEntry {
            sector_offset: 724,
            sector_count: 47,
            byte_len: 95274,
        },
        TileSectorEntry {
            sector_offset: 771,
            sector_count: 42,
            byte_len: 85553,
        },
        TileSectorEntry {
            sector_offset: 813,
            sector_count: 50,
            byte_len: 100972,
        },
        TileSectorEntry {
            sector_offset: 863,
            sector_count: 38,
            byte_len: 77203,
        },
        TileSectorEntry {
            sector_offset: 901,
            sector_count: 35,
            byte_len: 70378,
        },
        TileSectorEntry {
            sector_offset: 936,
            sector_count: 40,
            byte_len: 80676,
        },
        TileSectorEntry {
            sector_offset: 976,
            sector_count: 51,
            byte_len: 103964,
        },
        TileSectorEntry {
            sector_offset: 1027,
            sector_count: 54,
            byte_len: 109624,
        },
        TileSectorEntry {
            sector_offset: 1081,
            sector_count: 49,
            byte_len: 98855,
        },
        TileSectorEntry {
            sector_offset: 1130,
            sector_count: 50,
            byte_len: 102188,
        },
        TileSectorEntry {
            sector_offset: 1180,
            sector_count: 54,
            byte_len: 108999,
        },
        TileSectorEntry {
            sector_offset: 1234,
            sector_count: 48,
            byte_len: 97215,
        },
    ],
];

/// The 16 level-palette core reference colours in code order 0..=15.
pub static CLUT_RGB: [(u8, u8, u8); 16] = [
    (0, 0, 0),
    (60, 62, 68),
    (74, 76, 84),
    (232, 232, 240),
    (216, 40, 60),
    (46, 90, 52),
    (107, 84, 50),
    (122, 96, 144),
    (138, 31, 176),
    (255, 138, 16),
    (242, 242, 242),
    (0, 210, 255),
    (42, 46, 56),
    (90, 70, 50),
    (58, 90, 122),
    (255, 46, 136),
];

/// Streams and decompresses 16-bit BGR555 pixels on-the-fly using an 8192-byte ring buffer.
/// Emits each 16-bit halfword directly to the consumer callback with zero heap allocations.
#[inline(never)]
pub fn decompress_stream<F: FnMut(u16)>(
    src: &[u8],
    total_halfwords: usize,
    ring: &mut [u8; STREAM_WINDOW],
    mut emit: F,
) {
    let total_bytes = total_halfwords * 2;
    let mut in_pos = 0;
    let mut out_pos = 0;
    let mut lo_byte: u8 = 0;
    let mut has_lo = false;

    while out_pos < total_bytes && in_pos < src.len() {
        let flag = src[in_pos];
        in_pos += 1;
        for bit in 0..8 {
            if out_pos >= total_bytes || in_pos >= src.len() {
                break;
            }
            if (flag & (1 << bit)) != 0 {
                let b = src[in_pos];
                in_pos += 1;
                ring[out_pos % STREAM_WINDOW] = b;
                out_pos += 1;
                if !has_lo {
                    lo_byte = b;
                    has_lo = true;
                } else {
                    emit((lo_byte as u16) | ((b as u16) << 8));
                    has_lo = false;
                }
            } else {
                if in_pos + 3 > src.len() {
                    return;
                }
                let b0 = src[in_pos] as usize;
                let b1 = src[in_pos + 1] as usize;
                let mlen = (src[in_pos + 2] as usize) + 3;
                in_pos += 3;
                let dist = (b0 << 8) | b1;
                for _ in 0..mlen {
                    if out_pos >= total_bytes {
                        break;
                    }
                    let b = ring[(out_pos.wrapping_sub(dist)) % STREAM_WINDOW];
                    ring[out_pos % STREAM_WINDOW] = b;
                    out_pos += 1;
                    if !has_lo {
                        lo_byte = b;
                        has_lo = true;
                    } else {
                        emit((lo_byte as u16) | ((b as u16) << 8));
                        has_lo = false;
                    }
                }
            }
        }
    }
}

/// Decompresses a 15-bit texture stream into a destination slice of halfwords.
pub fn decompress_to_slice(src: &[u8], dst: &mut [u16]) {
    let mut ring = [0u8; STREAM_WINDOW];
    let mut idx = 0;
    let max_len = dst.len();
    decompress_stream(src, max_len, &mut ring, |halfword| {
        if idx < max_len {
            dst[idx] = halfword;
            idx += 1;
        }
    });
}
