//! Per-circuit visual texture metadata and JPEG streaming index.
//!
//! Generated by `tools/track_cook/build_atlas.py`. Do not edit by hand.

/// Visual block dimension in texels (1024x1024).
pub const BLOCK_DIM: usize = 1024;
/// Width of a single visual block in texels.
pub const WIDTH: usize = 1024;
/// Height of a single visual block in texels.
pub const HEIGHT: usize = 1024;
/// Decompressed VRAM tile dimension in texels (64x64).
pub const TILE_DIM: usize = 64;
/// Number of 64x64 tiles along each axis of a 1024x1024 block (16).
pub const TILES_PER_BLOCK_AXIS: usize = 16;
/// Total number of 64x64 tiles per 1024x1024 block (256).
pub const TILES_PER_BLOCK: usize = 256;
/// Number of authored circuits, one 1024x1024 JPEG block each.
pub const COUNT: usize = 4;
/// Maximum bytes per 1024x1024 compressed JPEG block (200 KB = 204,800 bytes).
pub const BLOCK_MAX_BYTES: usize = 204800;
/// Number of 2048-byte CD sectors allocated per JPEG block (100 sectors = 200 KB).
pub const BLOCK_SECTORS: usize = 100;
/// Restart marker interval in MCUs (4 MCUs = 64x16 pixels).
pub const RESTART_INTERVAL: usize = 4;
/// Total restart intervals in one 1024x1024 block.
pub const RESTART_INTERVAL_COUNT: usize = 1024;
/// Raw uncompressed 16-bit BGR555 halfwords per 64x64 tile.
pub const RAW_TILE_HALFWORDS: usize = TILE_DIM * TILE_DIM;
/// Raw uncompressed byte count per 64x64 tile (8,192 bytes = 8 KB).
pub const RAW_TILE_BYTES: usize = RAW_TILE_HALFWORDS * 2;
/// Name of the track visual asset file on the CD-ROM disc.
pub const TRACKS_BIN_NAME: &[u8] = b"TRACKS.BIN";
/// Name of the Cape Town 10 km^2 city visual asset file on the CD-ROM disc.
pub const CAPETOWN_BIN_NAME: &[u8] = b"CAPETOWN.BIN";
/// Name of the Melbourne 10 km^2 city visual asset file on the CD-ROM disc.
pub const MELBOURNE_BIN_NAME: &[u8] = b"MELBOURNE.BIN";
/// Name of the London 10 km^2 city visual asset file on the CD-ROM disc.
pub const LONDON_BIN_NAME: &[u8] = b"LONDON.BIN";

/// CD-ROM sector index entry for a compressed 1024x1024 JPEG block in TRACKS.BIN.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct TileSectorEntry {
    /// 2048-byte sector offset from the start of TRACKS.BIN.
    pub sector_offset: u32,
    /// Number of 2048-byte CD sectors allocated for this block.
    pub sector_count: u32,
    /// Exact payload length of the compressed JPEG stream in bytes.
    pub byte_len: u32,
}

/// Streaming compressed 1024x1024 JPEG block sector index [circuit].
pub static CIRCUIT_BLOCK_SECTORS: [TileSectorEntry; COUNT] = [
    TileSectorEntry {
        sector_offset: 0,
        sector_count: 100,
        byte_len: 179628,
    },
    TileSectorEntry {
        sector_offset: 100,
        sector_count: 100,
        byte_len: 186948,
    },
    TileSectorEntry {
        sector_offset: 200,
        sector_count: 100,
        byte_len: 190461,
    },
    TileSectorEntry {
        sector_offset: 300,
        sector_count: 100,
        byte_len: 204783,
    },
];

/// Cape Town 10 km^2 3x3 block sector mapping [block_y * 3 + block_x].
pub static CAPETOWN_BLOCK_SECTORS: [TileSectorEntry; 9] = [
    TileSectorEntry {
        sector_offset: 0,
        sector_count: 100,
        byte_len: 137276,
    },
    TileSectorEntry {
        sector_offset: 100,
        sector_count: 100,
        byte_len: 200201,
    },
    TileSectorEntry {
        sector_offset: 200,
        sector_count: 100,
        byte_len: 202761,
    },
    TileSectorEntry {
        sector_offset: 300,
        sector_count: 100,
        byte_len: 201551,
    },
    TileSectorEntry {
        sector_offset: 400,
        sector_count: 100,
        byte_len: 202370,
    },
    TileSectorEntry {
        sector_offset: 500,
        sector_count: 100,
        byte_len: 204573,
    },
    TileSectorEntry {
        sector_offset: 600,
        sector_count: 100,
        byte_len: 201942,
    },
    TileSectorEntry {
        sector_offset: 700,
        sector_count: 100,
        byte_len: 201336,
    },
    TileSectorEntry {
        sector_offset: 800,
        sector_count: 100,
        byte_len: 203666,
    },
];

/// Melbourne 10 km^2 3x3 block sector mapping [block_y * 3 + block_x].
pub static MELBOURNE_BLOCK_SECTORS: [TileSectorEntry; 9] = [
    TileSectorEntry {
        sector_offset: 0,
        sector_count: 100,
        byte_len: 202858,
    },
    TileSectorEntry {
        sector_offset: 100,
        sector_count: 100,
        byte_len: 203626,
    },
    TileSectorEntry {
        sector_offset: 200,
        sector_count: 100,
        byte_len: 202335,
    },
    TileSectorEntry {
        sector_offset: 300,
        sector_count: 100,
        byte_len: 202009,
    },
    TileSectorEntry {
        sector_offset: 400,
        sector_count: 100,
        byte_len: 202514,
    },
    TileSectorEntry {
        sector_offset: 500,
        sector_count: 100,
        byte_len: 201905,
    },
    TileSectorEntry {
        sector_offset: 600,
        sector_count: 100,
        byte_len: 201373,
    },
    TileSectorEntry {
        sector_offset: 700,
        sector_count: 100,
        byte_len: 204069,
    },
    TileSectorEntry {
        sector_offset: 800,
        sector_count: 100,
        byte_len: 201445,
    },
];

/// London 10 km^2 3x3 block sector mapping [block_y * 3 + block_x].
pub static LONDON_BLOCK_SECTORS: [TileSectorEntry; 9] = [
    TileSectorEntry {
        sector_offset: 0,
        sector_count: 100,
        byte_len: 201632,
    },
    TileSectorEntry {
        sector_offset: 100,
        sector_count: 100,
        byte_len: 203679,
    },
    TileSectorEntry {
        sector_offset: 200,
        sector_count: 100,
        byte_len: 201511,
    },
    TileSectorEntry {
        sector_offset: 300,
        sector_count: 100,
        byte_len: 203232,
    },
    TileSectorEntry {
        sector_offset: 400,
        sector_count: 100,
        byte_len: 204505,
    },
    TileSectorEntry {
        sector_offset: 500,
        sector_count: 100,
        byte_len: 204588,
    },
    TileSectorEntry {
        sector_offset: 600,
        sector_count: 100,
        byte_len: 203685,
    },
    TileSectorEntry {
        sector_offset: 700,
        sector_count: 100,
        byte_len: 202005,
    },
    TileSectorEntry {
        sector_offset: 800,
        sector_count: 100,
        byte_len: 201521,
    },
];

/// Alias matching single-entry lookup for backwards compatibility.
pub static CIRCUIT_TILE_SECTORS: [TileSectorEntry; COUNT] = CIRCUIT_BLOCK_SECTORS;

/// The 16 level-palette core reference colours in code order 0..=15.
pub static CLUT_RGB: [(u8, u8, u8); 16] = [
    (0, 0, 0),
    (60, 62, 68),
    (74, 76, 84),
    (232, 232, 240),
    (216, 40, 60),
    (46, 90, 52),
    (107, 84, 50),
    (122, 96, 144),
    (138, 31, 176),
    (255, 138, 16),
    (242, 242, 242),
    (0, 210, 255),
    (42, 46, 56),
    (90, 70, 50),
    (58, 90, 122),
    (255, 46, 136),
];
